### ISSUE TITLE
目录问题

### ISSUE THREAD

**Issue by plane-hjh** [sijinglei/vue-tree-table#1]
你好，想请问一下PC目录下的tree-table-bak有什么作用吗

**Comment by sijinglei** [comment]
> 你好，想请问一下PC目录下的tree-table-bak有什么作用吗
没有什么作用，就是两种树结构，做了一个备份。

**Comment by sijinglei** [comment]
> 你好，想请问一下PC目录下的tree-table-bak有什么作用吗
初始化数据时，把这个设置为`true`就行了
m.isExpand = true
